
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopNavbar from "@/packages/ui/src/entities/TopNavbar/TopNavbar.component";
import Footer from "@/packages/ui/src/entities/Footer/Footer.component";
import MainNavbar from "@/packages/ui/src/entities/MainNavbar/MainNavbar.component";
import { Providers } from "@/packages/store/provider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <div>
          <TopNavbar/>
          <MainNavbar />
        </div>
          {children}
        <div>
            <Footer/>
        </div>
        </Providers>
      </body>
      
    </html>
  );
}
