export const iconSquad = [
    { icon: '/logotypes/logo/recruit.svg' },
    { icon: '/logotypes/logo/vympel.svg' },
    { icon: '/logotypes/logo/alpha.svg' },
    { icon: '/logotypes/logo/sso.svg' },
    { icon: '/logotypes/logo/22spn.svg' },
    { icon: '/logotypes/logo/grom.svg' },
    { icon: '/logotypes/logo/ksk.svg' },
    { icon: '/logotypes/logo/seal.svg' },
    { icon: '/logotypes/logo/tfb.svg' },
    { icon: '/logotypes/logo/raid.svg' },
    { icon: '/logotypes/logo/nesher.svg' },
    { icon: '/logotypes/logo/ezapac.svg' },
    { icon: '/logotypes/logo/arystan.svg' },
    { icon: '/logotypes/logo/sso_rb.svg' },
    { icon: '/logotypes/logo/amf.svg' },
    { icon: '/logotypes/logo/jiaolong.svg' },
    { icon: '/logotypes/logo/cst.svg' },
    { icon: '/logotypes/logo/bope.svg' },
]